
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightUMINUSLIST LISTCHAR ID NUMBER PLUS MINUS TIMES DIVIDE EQUALS LPAREN RPAREN COMMA UNION STDDEV VARIAN COMBI RANGE TRIM COMPLEM AVG INTER MODE MEDIAN PARTIAL PERMU CIRPERstatement : AVG LPAREN LIST RPARENstatement : PERMU LPAREN LISTCHAR RPARENstatement : PERMU LPAREN LIST RPARENstatement : CIRPER LPAREN NUMBER RPARENstatement : COMBI LPAREN LIST RPARENstatement : COMBI LPAREN LISTCHAR RPARENstatement : MODE LPAREN LIST RPARENstatement : MEDIAN LPAREN LIST RPARENstatement : TRIM LPAREN LIST RPARENstatement : UNION LPAREN LIST COMMA LIST RPARENstatement : INTER LPAREN LIST COMMA LIST RPARENstatement : COMPLEM LPAREN LIST COMMA LIST RPARENstatement : VARIAN LPAREN LIST RPARENstatement : STDDEV LPAREN LIST RPARENstatement : ID EQUALS expressionstatement : expressionexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expressionexpression : MINUS expression %prec UMINUSexpression : LPAREN expression RPARENexpression : LISTexpression : NUMBERexpression : IDstatement : PARTIAL LPAREN LIST RPARENstatement : RANGE LPAREN LIST RPAREN'
    
_lr_action_items = {'TRIM':([0,],[1,]),'PARTIAL':([0,],[2,]),'MODE':([0,],[4,]),'LISTCHAR':([27,28,],[50,51,]),'COMMA':([48,53,60,],[70,75,81,]),'VARIAN':([0,],[5,]),'COMPLEM':([0,],[6,]),'EQUALS':([15,],[35,]),'COMBI':([0,],[8,]),'LIST':([0,12,21,22,23,24,25,26,27,28,29,30,33,35,36,37,38,39,40,41,42,70,75,81,],[9,9,9,44,45,46,47,48,49,52,53,54,55,9,58,59,60,9,9,9,9,82,83,84,]),'UNION':([0,],[10,]),'AVG':([0,],[11,]),'$end':([3,9,15,19,20,31,32,57,61,62,63,64,65,66,67,68,69,71,72,73,74,76,77,78,79,80,85,86,87,],[0,-23,-25,-16,-24,-25,-21,-15,-18,-19,-17,-20,-22,-9,-26,-7,-13,-3,-2,-6,-5,-1,-27,-4,-8,-14,-12,-10,-11,]),'MINUS':([0,9,12,15,19,20,21,31,32,35,39,40,41,42,43,57,61,62,63,64,65,],[12,-23,12,-25,39,-24,12,-25,-21,12,12,12,12,12,39,39,-18,-19,-17,-20,-22,]),'RANGE':([0,],[13,]),'RPAREN':([9,20,31,32,43,44,45,46,47,49,50,51,52,54,55,56,58,59,61,62,63,64,65,82,83,84,],[-23,-24,-25,-21,65,66,67,68,69,71,72,73,74,76,77,78,79,80,-18,-19,-17,-20,-22,85,86,87,]),'CIRPER':([0,],[14,]),'ID':([0,12,21,35,39,40,41,42,],[15,31,31,31,31,31,31,31,]),'MEDIAN':([0,],[16,]),'PLUS':([9,15,19,20,31,32,43,57,61,62,63,64,65,],[-23,-25,41,-24,-25,-21,41,41,-18,-19,-17,-20,-22,]),'STDDEV':([0,],[17,]),'DIVIDE':([9,15,19,20,31,32,43,57,61,62,63,64,65,],[-23,-25,42,-24,-25,-21,42,42,42,-19,42,-20,-22,]),'INTER':([0,],[18,]),'PERMU':([0,],[7,]),'TIMES':([9,15,19,20,31,32,43,57,61,62,63,64,65,],[-23,-25,40,-24,-25,-21,40,40,40,-19,40,-20,-22,]),'NUMBER':([0,12,21,34,35,39,40,41,42,],[20,20,20,56,20,20,20,20,20,]),'LPAREN':([0,1,2,4,5,6,7,8,10,11,12,13,14,16,17,18,21,35,39,40,41,42,],[21,22,23,24,25,26,27,28,29,30,21,33,34,36,37,38,21,21,21,21,21,21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,12,21,35,39,40,41,42,],[19,32,43,57,61,62,63,64,]),'statement':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> AVG LPAREN LIST RPAREN','statement',4,'p_statement_average','Probabilius.py',109),
  ('statement -> PERMU LPAREN LISTCHAR RPAREN','statement',4,'p_statement_permuCHAR','Probabilius.py',120),
  ('statement -> PERMU LPAREN LIST RPAREN','statement',4,'p_statement_permu','Probabilius.py',132),
  ('statement -> CIRPER LPAREN NUMBER RPAREN','statement',4,'p_statement_cirper','Probabilius.py',143),
  ('statement -> COMBI LPAREN LIST RPAREN','statement',4,'p_statement_combi','Probabilius.py',153),
  ('statement -> COMBI LPAREN LISTCHAR RPAREN','statement',4,'p_statement_combiCHAR','Probabilius.py',164),
  ('statement -> MODE LPAREN LIST RPAREN','statement',4,'p_statement_mode','Probabilius.py',176),
  ('statement -> MEDIAN LPAREN LIST RPAREN','statement',4,'p_statement_median','Probabilius.py',187),
  ('statement -> TRIM LPAREN LIST RPAREN','statement',4,'p_statement_trimmedmean','Probabilius.py',198),
  ('statement -> UNION LPAREN LIST COMMA LIST RPAREN','statement',6,'p_statement_union','Probabilius.py',209),
  ('statement -> INTER LPAREN LIST COMMA LIST RPAREN','statement',6,'p_statement_intersection','Probabilius.py',223),
  ('statement -> COMPLEM LPAREN LIST COMMA LIST RPAREN','statement',6,'p_statement_complement','Probabilius.py',238),
  ('statement -> VARIAN LPAREN LIST RPAREN','statement',4,'p_statement_varian','Probabilius.py',252),
  ('statement -> STDDEV LPAREN LIST RPAREN','statement',4,'p_statement_stddev','Probabilius.py',262),
  ('statement -> ID EQUALS expression','statement',3,'p_statement_assign','Probabilius.py',272),
  ('statement -> expression','statement',1,'p_statement_expr','Probabilius.py',281),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','Probabilius.py',286),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','Probabilius.py',287),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','Probabilius.py',288),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','Probabilius.py',289),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','Probabilius.py',301),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','Probabilius.py',306),
  ('expression -> LIST','expression',1,'p_expression_list','Probabilius.py',311),
  ('expression -> NUMBER','expression',1,'p_expression_number','Probabilius.py',316),
  ('expression -> ID','expression',1,'p_expression_name','Probabilius.py',321),
  ('statement -> PARTIAL LPAREN LIST RPAREN','statement',4,'p_statement_partial','Probabilius.py',333),
  ('statement -> RANGE LPAREN LIST RPAREN','statement',4,'p_statement_range','Probabilius.py',343),
]
