
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightUMINUSLIST LISTCHAR ID NUMBER PLUS MINUS TIMES DIVIDE EQUALS LPAREN RPAREN COMMA VARIAN PARTIAL TRIM AVG COMPLEM STDDEV PERMU RANGE CIRPER MODE UNION COMBI INTER MEDIANstatement : AVG LPAREN LIST RPARENstatement : PERMU LPAREN LISTCHAR RPARENstatement : PERMU LPAREN LIST RPARENstatement : CIRPER LPAREN LIST RPARENstatement : COMBI LPAREN LIST RPARENstatement : COMBI LPAREN LISTCHAR RPARENstatement : MODE LPAREN LIST RPARENstatement : MEDIAN LPAREN LIST RPARENstatement : TRIM LPAREN LIST RPARENstatement : UNION LPAREN LIST COMMA LIST RPARENstatement : INTER LPAREN LIST COMMA LIST RPARENstatement : COMPLEM LPAREN LIST COMMA LIST RPARENstatement : VARIAN LPAREN LIST RPARENstatement : STDDEV LPAREN LIST RPARENstatement : ID EQUALS expressionstatement : expressionexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expressionexpression : MINUS expression %prec UMINUSexpression : LPAREN expression RPARENexpression : LISTexpression : NUMBERexpression : IDstatement : PARTIAL LPAREN LIST RPARENstatement : RANGE LPAREN LIST RPAREN'
    
_lr_action_items = {'STDDEV':([0,],[2,]),'UNION':([0,],[3,]),'PLUS':([4,6,7,9,32,33,42,49,50,51,52,54,64,],[-23,-24,26,-25,-21,-25,26,-17,-18,-19,-20,26,-22,]),'LIST':([0,10,20,22,23,24,25,26,27,28,29,30,31,34,35,36,37,38,39,40,41,43,68,79,81,],[4,4,4,44,45,46,47,4,4,4,4,53,4,55,56,57,58,59,61,62,63,65,82,83,84,]),'DIVIDE':([4,6,7,9,32,33,42,49,50,51,52,54,64,],[-23,-24,29,-25,-21,-25,29,29,29,-19,-20,29,-22,]),'PERMU':([0,],[5,]),'NUMBER':([0,10,20,26,27,28,29,31,],[6,6,6,6,6,6,6,6,]),'EQUALS':([9,],[31,]),'RANGE':([0,],[1,]),'ID':([0,10,20,26,27,28,29,31,],[9,33,33,33,33,33,33,33,]),'MINUS':([0,4,6,7,9,10,20,26,27,28,29,31,32,33,42,49,50,51,52,54,64,],[10,-23,-24,27,-25,10,10,10,10,10,10,10,-21,-25,27,-17,-18,-19,-20,27,-22,]),'CIRPER':([0,],[14,]),'LISTCHAR':([25,38,],[48,60,]),'RPAREN':([4,6,32,33,42,44,45,47,48,49,50,51,52,53,55,56,57,58,59,60,61,63,64,82,83,84,],[-23,-24,-21,-25,64,66,67,69,70,-17,-18,-19,-20,71,72,73,74,75,76,77,78,80,-22,85,86,87,]),'TRIM':([0,],[12,]),'TIMES':([4,6,7,9,32,33,42,49,50,51,52,54,64,],[-23,-24,28,-25,-21,-25,28,28,28,-19,-20,28,-22,]),'PARTIAL':([0,],[11,]),'COMBI':([0,],[15,]),'MODE':([0,],[19,]),'VARIAN':([0,],[16,]),'$end':([4,6,7,9,18,32,33,49,50,51,52,54,64,66,67,69,70,71,72,73,74,75,76,77,78,80,85,86,87,],[-23,-24,-16,-25,0,-21,-25,-17,-18,-19,-20,-15,-22,-27,-14,-3,-2,-8,-26,-9,-1,-4,-5,-6,-13,-7,-10,-11,-12,]),'INTER':([0,],[17,]),'COMMA':([46,62,65,],[68,79,81,]),'MEDIAN':([0,],[8,]),'AVG':([0,],[13,]),'LPAREN':([0,1,2,3,5,8,10,11,12,13,14,15,16,17,19,20,21,26,27,28,29,31,],[20,22,23,24,25,30,20,34,35,36,37,38,39,40,41,20,43,20,20,20,20,20,]),'COMPLEM':([0,],[21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[18,]),'expression':([0,10,20,26,27,28,29,31,],[7,32,42,49,50,51,52,54,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> AVG LPAREN LIST RPAREN','statement',4,'p_statement_average','Probabilius.py',109),
  ('statement -> PERMU LPAREN LISTCHAR RPAREN','statement',4,'p_statement_permuCHAR','Probabilius.py',120),
  ('statement -> PERMU LPAREN LIST RPAREN','statement',4,'p_statement_permu','Probabilius.py',132),
  ('statement -> CIRPER LPAREN LIST RPAREN','statement',4,'p_statement_cirper','Probabilius.py',143),
  ('statement -> COMBI LPAREN LIST RPAREN','statement',4,'p_statement_combi','Probabilius.py',154),
  ('statement -> COMBI LPAREN LISTCHAR RPAREN','statement',4,'p_statement_combiCHAR','Probabilius.py',165),
  ('statement -> MODE LPAREN LIST RPAREN','statement',4,'p_statement_mode','Probabilius.py',177),
  ('statement -> MEDIAN LPAREN LIST RPAREN','statement',4,'p_statement_median','Probabilius.py',188),
  ('statement -> TRIM LPAREN LIST RPAREN','statement',4,'p_statement_trimmedmean','Probabilius.py',199),
  ('statement -> UNION LPAREN LIST COMMA LIST RPAREN','statement',6,'p_statement_union','Probabilius.py',210),
  ('statement -> INTER LPAREN LIST COMMA LIST RPAREN','statement',6,'p_statement_intersection','Probabilius.py',224),
  ('statement -> COMPLEM LPAREN LIST COMMA LIST RPAREN','statement',6,'p_statement_complement','Probabilius.py',239),
  ('statement -> VARIAN LPAREN LIST RPAREN','statement',4,'p_statement_varian','Probabilius.py',253),
  ('statement -> STDDEV LPAREN LIST RPAREN','statement',4,'p_statement_stddev','Probabilius.py',263),
  ('statement -> ID EQUALS expression','statement',3,'p_statement_assign','Probabilius.py',273),
  ('statement -> expression','statement',1,'p_statement_expr','Probabilius.py',282),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','Probabilius.py',287),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','Probabilius.py',288),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','Probabilius.py',289),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','Probabilius.py',290),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','Probabilius.py',302),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','Probabilius.py',307),
  ('expression -> LIST','expression',1,'p_expression_list','Probabilius.py',312),
  ('expression -> NUMBER','expression',1,'p_expression_number','Probabilius.py',317),
  ('expression -> ID','expression',1,'p_expression_name','Probabilius.py',322),
  ('statement -> PARTIAL LPAREN LIST RPAREN','statement',4,'p_statement_partial','Probabilius.py',334),
  ('statement -> RANGE LPAREN LIST RPAREN','statement',4,'p_statement_range','Probabilius.py',344),
]
